/:
  controller: Main
  action: home

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login
  
/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/refering:
  controller: Main
  action: refering

/portfolio:
  controller: Main
  action : portfolio

/project:
  controller: Main
  action: project

/page:
  controller: Main
  action: page