/:
  controller: Main
  action: home

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login
  
/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register
